### ISSUE TITLE
Add Latin-to-Balinese script support

### ISSUE THREAD

**Issue by masnormen** [masnormen/carakanjs#1]
Planning to implement it with a new function toBalinese() with different charlist (?)

**Comment by rahulkumarsingh73690** [comment]
Any update on this package?

**Comment by masnormen** [comment]
> Any update on this package?

I'm currently planning to refactor this package and support Javanese into Latin transliteration first in the future. No one knows surely when

**Comment by rahulkumarsingh73690** [comment]
I am using this package for the previous year. please update library

**Comment by masnormen** [comment]
what kind of update do you want to see? @rahulkumarsingh73690

**Comment by rahulkumarsingh73690** [comment]
This site gives different output why? https://www.kompiwin.com/translate-aksara/jawa/

and implement toBalinese()

**Comment by rahulkumarsingh73690** [comment]
support transliteration of Javanese script back to Latin

**Comment by masnormen** [comment]
Javanese -> Latin is implemented with #3.

If you want to request other features, please try to contribute. Thank you.

**Comment by rahulkumarsingh73690** [comment]
@masnormen

I love to contribute, but there is no proper contribution guide.

I found some issues in Latin -> Javanese translation.

When I tested it on (https://www.kompiwin.com/translate-aksara/jawa/) with the input "sss," it returned "꧋ꦱ꧀ꦱ꧀ꦱ꧀," but the carakanjs script returned nothing for the input "sss."

This is the issue I found while testing with dummy data

**Comment by masnormen** [comment]
@rahulkumarsingh73690 It's just the way Javanese script unicode character works. But in the Javanese context, it doesn't make sense. It's not Latin where you stack characters. Realistically, there's no way "sss" is gonna be written with Javanese script. Carakan is intended for real, everyday Javanese text, so it's discarded.

Also as far as I know, there's no definitive convention about how to write more than 2 _consecutive muted consonant_ in Javanese (there are multiple way to mute a consonant), so you will find different results from different sites :)

I probably need to change the transliterator engine later to allow this. So thank you, locking this for now
